# Generated by Django 4.2.9 on 2024-01-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comptes',
            fields=[
                ('compteid', models.AutoField(primary_key=True, serialize=False)),
                ('comptename', models.CharField(max_length=100)),
                ('comptetwitter', models.CharField(max_length=100)),
                ('comptegethub', models.CharField(max_length=100)),
                ('comptelinkedin', models.CharField(max_length=100)),
                ('compteadress', models.CharField(max_length=100)),
                ('comptetel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectsid', models.AutoField(primary_key=True, serialize=False)),
                ('projectsname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Staffmail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Stafftype', models.CharField(max_length=100)),
                ('Staffpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=100)),
                ('taskusers', models.CharField(max_length=100)),
            ],
        ),
    ]
