# Generated by Django 4.2.9 on 2024-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0002_alter_comptes_comptetel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptes',
            name='comptetel',
            field=models.IntegerField(),
        ),
    ]
