# Generated by Django 4.2.9 on 2024-01-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0003_alter_comptes_comptetel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptes',
            old_name='compteadress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='comptes',
            old_name='comptegethub',
            new_name='gethub',
        ),
        migrations.RenameField(
            model_name='comptes',
            old_name='compteid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comptes',
            old_name='comptelinkedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='comptes',
            old_name='comptename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comptes',
            old_name='comptetel',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='comptes',
            old_name='comptetwitter',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projectsid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projectsname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Staffmail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Staffpassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Stafftype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='taskid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='taskname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='taskusers',
            new_name='users',
        ),
    ]
