# Generated by Django 4.2.9 on 2024-02-02 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0005_taskspersonal_rename_tasks_tasksprofesionnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskspersonal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tasksprofesionnel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
