# Generated by Django 4.2.9 on 2024-02-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0006_taskspersonal_date_tasksprofesionnel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskspersonal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
