# Generated by Django 4.2.9 on 2024-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0007_taskspersonal_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.CharField(default='personal', max_length=100),
        ),
    ]
