# Generated by Django 4.2.9 on 2024-02-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0008_projects_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskspersonal',
            name='projectID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolistApp.projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
