# Generated by Django 4.2.9 on 2024-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0010_alter_taskspersonal_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
