# Generated by Django 4.2.9 on 2024-02-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0012_comptes_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptes',
            name='mail',
        ),
    ]
