# Generated by Django 4.2.9 on 2024-02-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0013_remove_comptes_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksprofesionnel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
