# Generated by Django 4.2.9 on 2024-02-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0014_tasksprofesionnel_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksprofesionnel',
            name='users',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
