# Generated by Django 4.2.9 on 2024-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0015_alter_tasksprofesionnel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksprofesionnel',
            name='users',
            field=models.CharField(max_length=100),
        ),
    ]
