# Generated by Django 4.2.9 on 2024-02-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0016_alter_tasksprofesionnel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksprofesionnel',
            name='users',
        ),
    ]
