# Generated by Django 5.0.3 on 2024-03-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0018_tasksprofesionnel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksprofesionnel',
            name='projectID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolistApp.projects'),
        ),
    ]
