# Generated by Django 5.0.3 on 2024-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0019_tasksprofesionnel_projectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='mail',
        ),
        migrations.AddField(
            model_name='staff',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mail',
            field=models.CharField(max_length=100),
        ),
    ]
