# Generated by Django 5.0.3 on 2024-03-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0020_remove_projects_mail_staff_id_alter_staff_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='staffID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolistApp.staff'),
        ),
    ]
