# Generated by Django 5.0.3 on 2024-03-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0021_projects_staffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='staffID',
        ),
    ]
