# Generated by Django 5.0.3 on 2024-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0023_projects_staffid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptes',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
