# Generated by Django 5.0.3 on 2024-04-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0024_comptes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptes',
            name='staffID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolistApp.staff'),
        ),
    ]
