# Generated by Django 5.0.3 on 2024-04-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0025_comptes_staffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comptes',
            name='staffID',
        ),
    ]
