# Generated by Django 5.0.3 on 2024-04-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0026_remove_comptes_image_remove_comptes_staffid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptes',
            name='image',
            field=models.ImageField(blank=True, default='imagemohamed.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='comptes',
            name='staffID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolistApp.staff'),
        ),
    ]
